### ISSUE TITLE
请问FAD相关的代码在哪部分？

### ISSUE THREAD

**Issue by CUMTGG** [ylwhxht/L4DR#1]
很好的工作！！有一个问题：FAD相关的代码在哪部分？

**Comment by ylwhxht** [comment]
> 很好的工作！！有一个问题：FAD相关的代码在哪部分？

本质上是个前景分割的任务，我们使用了PointNet2MSG的点级3Dbackbone和PointHeadPreMask分割头实现。详见[L4DR配置文件](https://github.com/ylwhxht/L4DR/blob/main/tools/cfgs/VoD_models/L4DR.yaml)。具体实现可以根据对应模块找到代码。

**Comment by CUMTGG** [comment]
非常感谢！

**Comment by ylwhxht** [comment]
> 非常感谢！

不客气
