### ISSUE TITLE
K-Radar数据集相关的配置文件和代码

### ISSUE THREAD

**Issue by M-Y-Huang** [ylwhxht/L4DR#3]
很清晰的方法，点赞！
请问作者，是否计划上传K-Radar数据集相关的配置文件和代码。
另外还有一个问题请教，您是否做过不包含毫米波雷达多普勒速度的相关实验，如果有的话，相比论文方法的性能差距如何。
非常感谢！

**Comment by ylwhxht** [comment]
> 很清晰的方法，点赞！ 请问作者，是否计划上传K-Radar数据集相关的配置文件和代码。 另外还有一个问题请教，您是否做过不包含毫米波雷达多普勒速度的相关实验，如果有的话，相比论文方法的性能差距如何。 非常感谢！

感谢您的关注，后续抽空会再上传K-radar相关的代码和配置，但是由于两个数据集是完全使用不同的代码架构，需要重新整理，可能会花费一点时间，近期不太方便。
至于不包含毫米波雷达多普勒速度的相关实验部分，我们在K-radar数据集上的结果就是不包含多普勒信息的，因为K-radar原始数据过大，我们只能下载他们提供的稀疏4D雷达点云，而这是不包含毫米波雷达多普勒速度的。
但是我感觉你想问的是直接对比是否使用速度的影响，这部分我们没有进行过消融，如果你有兴趣可以通过VoD上开源代码进行消融。

**Comment by M-Y-Huang** [comment]
好的，非常感谢。期待您的上传以及后续的工作。
